name: CI - Design Patterns

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: order-service-patterns

    steps:
      # 1. Descarga el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configura JDK 21 (usado por Maven)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Cachea las dependencias de Maven para acelerar builds futuros
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('order-service-patterns/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4. Compila y ejecuta tests con Maven
      - name: Build with Maven
        run: mvn clean package --no-transfer-progress

      # 5. Construye la imagen Docker a partir del Dockerfile
      - name: Build Docker image
        run: docker build -t design-patterns-app .
